apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::495345689226:role/eksctl-cicd-demo-nodegroup-ng-e56-NodeInstanceRole-CNUJV4NGJ4HZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::495345689226:role/UdacityFlaskCICDDeployRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-11T14:22:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1861"
  uid: e3ef9a93-62a9-46aa-9eae-0623baf1b751
